ALTER TABLE items ADD COLUMN photo_1 TEXT NULL;
ALTER TABLE items ADD COLUMN photo_2 TEXT NULL;
ALTER TABLE items ADD COLUMN photo_3 TEXT NULL;
ALTER TABLE items ADD COLUMN photo_4 TEXT NULL;
ALTER TABLE items ADD COLUMN photo_5 TEXT NULL;
ALTER TABLE items ADD COLUMN item_link TEXT NULL;
ALTER TABLE items ADD COLUMN video_link TEXT NULL;
